### ISSUE TITLE
Install phpdox 0.11.2 issue

### ISSUE THREAD

**Issue by medbak** [theseer/phpdox#345] opened 2018-11-13 08:23 UTC
When trying to install phpdox via composer : "composer require theseer/phpdox", I got this error message:

Using version ^0.11.2 for theseer/phpdox
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install sebastian/phpcpd 4.1.0
    - Conclusion: don't install sebastian/phpcpd 4.0.0
    - Installation request for theseer/phpdox ^0.11.2 -> satisfiable by theseer/phpdox[0.11.2].
    - Installation request for sebastian/phpcpd ^4.0 -> satisfiable by sebastian/phpcpd[4.0.0, 4.1.0, 4.0.x-dev].
    - theseer/phpdox 0.11.2 requires phpunit/php-timer ^1.0 -> satisfiable by phpunit/php-timer[1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.x-dev].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.3].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.4].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.5].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.6].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.7].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.8].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.9].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.x-dev].
    - sebastian/phpcpd 4.0.x-dev requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0, 2.0.x-dev].
    - Conclusion: don't install phpunit/php-timer 2.0.0

Installation failed, reverting ./composer.json to its original content.

Even, if I use "theseer/phpdox":"*" inside the composer, the installed phpdox version is '0.9.0' 
  - Installing theseer/fxsl (1.1.1): Loading from cache
  - Installing theseer/directoryscanner (1.3.2): Loading from cache
  - Installing theseer/phpdox (0.9.0): Loading from cache

and when i tried to run phpdox using this command "vendor/bin/phpdox", i got this message :
phpDox 0.8.2-dev - Copyright (C) 2010 - 2018 by Arne Blankerts

[13.11.2018 - 08:07:01] Using config file './phpdox.xml'
[13.11.2018 - 08:07:01] Registered collector backend 'parser'
[13.11.2018 - 08:07:01] Registered enricher 'build'
[13.11.2018 - 08:07:01] Registered enricher 'git'
[13.11.2018 - 08:07:01] Registered enricher 'checkstyle'
[13.11.2018 - 08:07:01] Registered enricher 'phpcs'
[13.11.2018 - 08:07:01] Registered enricher 'pmd'
[13.11.2018 - 08:07:01] Registered enricher 'phpunit'
[13.11.2018 - 08:07:01] Registered enricher 'phploc'
[13.11.2018 - 08:07:01] Registered output engine 'xml'
[13.11.2018 - 08:07:01] Registered output engine 'html'

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.2.10-0ubuntu0.18.04.1 (Linux)
PHPDox Version: 0.8.2-dev
ErrorException: E_WARNING 
Location: /home/****/Bureau/******/vendor/theseer/phpdox/src/shared/FileInfoCollection.php (Line 67)

count(): Parameter must be an array or an object that implements Countable

#0 /home/*****/Bureau/******/vendor/theseer/phpdox/src/shared/FileInfoCollection.php(67): count()
#1 /home/*****/Bureau/******/vendor/theseer/phpdox/src/shared/FileInfoCollection.php(53): TheSeer\phpDox\FileInfoCollection->count()
#2 /home/*****/Bureau/*******/vendor/theseer/phpdox/src/bootstrap/Bootstrap.php(56): TheSeer\phpDox\FileInfoCollection->valid()
#3 /home/******/Bureau/*******/vendor/theseer/phpdox/src/CLI.php(130): TheSeer\phpDox\Bootstrap->load()
#4 /home/******/Bureau/*******/vendor/theseer/phpdox/phpdox(67): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment] 2018-11-16 19:30
Duplicate of #328.

See https://github.com/theseer/phpdox/issues/328#issuecomment-372602708 for details.

**Closed by theseer** 2018-11-16 19:30 UTC

**Comment by medbak** [comment] 2018-11-19 09:00
Ok, I will investigate see it. Thanks.
