### ISSUE TITLE
Date()  Bug - Causes Script to Terminate

### ISSUE THREAD

**Issue by Shane-Bryan** [theseer/phpdox#241] opened 2015-08-02 09:50 UTC
Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.3.29 (Linux)
PHPDox Version: 0.8.0
ErrorException: E_WARNING
Location: phar:///usr/local/bin/phpdox/phpdox/shared/Version.php (Line 71)

date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead

#0 phar:///usr/local/bin/phpdox/phpdox/shared/Version.php(71): date()
#1 phar:///usr/local/bin/phpdox/phpdox/CLI.php(216): TheSeer\phpDox\Version->getInfoString()
#2 phar:///usr/local/bin/phpdox/phpdox/CLI.php(175): TheSeer\phpDox\CLI->showVersion()
#3 /usr/local/bin/phpdox(450): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment] 2015-08-02 10:26
Duplicate of #103

**Comment by theseer** [comment] 2015-08-02 10:27
Please also use the latest release version before reporting issues to ease reproduction.

**Closed by theseer** 2015-08-02 10:26 UTC
