### ISSUE TITLE
Class 'PhpParser\ErrorHandler\Throwing' not found

### ISSUE THREAD

**Issue by conorgahan** [theseer/phpdox#295] opened 2016-12-01 09:17 UTC
```
PHP Version: 7.0.12 (Linux)
PHPDox Version: 0.8.2-dev
Exception: Error (Code: 0)
Location: /vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php (Line 28)

Class 'PhpParser\ErrorHandler\Throwing' not found

#0 /vendor/theseer/phpdox/src/collector/Collector.php(141): TheSeer\phpDox\Collector\Backend\PHPParser->parse()
#1 /vendor/theseer/phpdox/src/collector/Collector.php(105): TheSeer\phpDox\Collector\Collector->processFile()
#2 /vendor/theseer/phpdox/src/Application.php(122): TheSeer\phpDox\Collector\Collector->run()
#3 /vendor/theseer/phpdox/src/CLI.php(161): TheSeer\phpDox\Application->runCollector()
#4 /vendor/theseer/phpdox/phpdox(67): TheSeer\phpDox\CLI->run()
```

**Comment by theseer** [comment] 2016-12-01 10:41
Duplicate of #289

**Closed by theseer** 2016-12-01 10:41 UTC
