### ISSUE TITLE
Error TokenFileException 

### ISSUE THREAD

**Issue by Climberdav** [theseer/phpdox#316] opened 2017-11-22 10:02 UTC
Hello,

I have this Issue and don't know ho to fix it. 
```bash
Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.6.25 (WINNT)
PHPDox Version: 0.11.0-dev
Exception: TheSeer\phpDox\Generator\TokenFileException (Code: 1)
Location: E:\_PHP\xxx\vendor\theseer\phpdox\src\generator\project\TokenFile.php (Line 19)

File 'file:/E:/_PHP/xxx/build/phpdox/tokens/AppBundle/AppBundle.php.xml' not found

#0 E:\_PHP\xxx\vendor\theseer\phpdox\src\generator\Generator.php(153): TheSeer\phpDox\Generator\TokenFileIterator->current()
#1 E:\_PHP\xxx\vendor\theseer\phpdox\src\generator\Generator.php(146): TheSeer\phpDox\Generator\Generator->processTokenFiles()
#2 E:\_PHP\xxx\vendor\theseer\phpdox\src\Application.php(241): TheSeer\phpDox\Generator\Generator->run()
#3 E:\_PHP\xxx\vendor\theseer\phpdox\src\CLI.php(165): TheSeer\phpDox\Application->runGenerator()
#4 E:\_PHP\xxx\vendor\theseer\phpdox\phpdox(80): TheSeer\phpDox\CLI->run()

```
I installed it with `composer require --dev theseer/phpdox 0.10.1` but I install version `0.11.0-dev`

Any idea ? 
Thanks

**Comment by theseer** [comment] 2017-12-06 22:51
Duplicate of #271

**Closed by theseer** 2017-12-06 22:51 UTC
