### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by LXkennstenich** [theseer/phpdox#369] opened 2019-09-08 12:52 UTC
PHP Version: 7.2.19-0ubuntu0.18.04.2 (Linux)
PHPDox Version: 0.8.0
ErrorException: E_WARNING 
Location: phar:///usr/local/bin/phpdox/phpdox/shared/FileInfoCollection.php (Line 67)

count(): Parameter must be an array or an object that implements Countable

#0 phar:///usr/local/bin/phpdox/phpdox/shared/FileInfoCollection.php(67): count()
#1 phar:///usr/local/bin/phpdox/phpdox/shared/FileInfoCollection.php(53): TheSeer\phpDox\FileInfoCollection->count()
#2 phar:///usr/local/bin/phpdox/phpdox/bootstrap/Bootstrap.php(56): TheSeer\phpDox\FileInfoCollection->valid()
#3 phar:///usr/local/bin/phpdox/phpdox/CLI.php(129): TheSeer\phpDox\Bootstrap->load()
#4 /usr/local/bin/phpdox(449): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment] 2019-09-13 19:23
Duplicate of already fixed #315.

Please upgrade, 0.8.0 is really old and outdated.

**Closed by theseer** 2019-09-13 19:23 UTC
