### ISSUE TITLE
Oups... phpDox encountered a problem and has terminated!

### ISSUE THREAD

**Issue by mostwanted1976** [theseer/phpdox#265] opened 2016-03-01 16:53 UTC
I got an error and the console output advised me to report this potential bug:

     [exec] [01.03.2016 - 16:45:37] Saving results to directory 'Build/WorkingDirectoryForTools/phpdox'
     [exec] [01.03.2016 - 16:45:37] Collector process completed
     [exec] 
     [exec] [01.03.2016 - 16:45:37] Starting generator
     [exec] [01.03.2016 - 16:45:37] Loading enrichers
     [exec] [01.03.2016 - 16:45:37] Enricher GIT information initialized successfully
     [exec] [01.03.2016 - 16:45:37] Enricher PHPLoc xml initialized successfully
     [exec] [01.03.2016 - 16:45:37] Enricher PHPCS XML initialized successfully
     [exec] [01.03.2016 - 16:45:37] Enricher PHPMessDetector XML initialized successfully
     [exec] [01.03.2016 - 16:45:37] Enricher Build Information initialized successfully
     [exec] [01.03.2016 - 16:45:37] Starting event loop.
     [exec] 
     [exec] I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/components.xsl"
     [exec] I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/functions.xsl"
     [exec] I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/synopsis.xsl"
     [exec] 
     [exec] 
     [exec] Oups... phpDox encountered a problem and has terminated!
     [exec] 
     [exec] It most likely means you've found a bug, so please file a report for this
     [exec] and paste the following details and the stacktrace (if given) along:
     [exec] 
     [exec] PHP Version: 5.6.16 (Darwin)
     [exec] PHPDox Version: 0.8.1.1
     [exec] ErrorException: E_WARNING 
     [exec] Location: phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/vendor/theseer/fxsl/src/fxsltprocessor.php (Line 192)
     [exec] 
     [exec] XSLTProcessor::transformToDoc(): No stylesheet associated to this object
     [exec] 
     [exec] #0 phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/vendor/theseer/fxsl/src/fxsltprocessor.php(192): XSLTProcessor->transformToDoc()
     [exec] #1 phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/phpdox/generator/engine/html/Html.php(208): TheSeer\fXSL\fXSLTProcessor->transformToDoc()
     [exec] #2 unknown(0): TheSeer\phpDox\Generator\Engine\Html->buildClass()
     [exec] #3 phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/phpdox/generator/Generator.php(203): call_user_func()
     [exec] #4 phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/phpdox/generator/Generator.php(277): TheSeer\phpDox\Generator\Generator->handleEvent()
     [exec] #5 phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/phpdox/generator/Generator.php(249): TheSeer\phpDox\Generator\Generator->processClass()
     [exec] #6 phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/phpdox/generator/Generator.php(142): TheSeer\phpDox\Generator\Generator->processWithNamespace()
     [exec] #7 phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/phpdox/Application.php(241): TheSeer\phpDox\Generator\Generator->run()
     [exec] #8 phar:///Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox/phpdox/CLI.php(165): TheSeer\phpDox\Application->runGenerator()
     [exec] #9 /Users/mostwanted/Projects/MyProject/Build/In2codeBuild/Tools/phpdox(451): TheSeer\phpDox\CLI->run()

Any idea what could be the problem here?

**Comment by theseer** [comment] 2016-03-08 12:38
Duplicate of #255

**Closed by theseer** 2016-03-08 12:38 UTC
