### ISSUE TITLE
Windows 8 Error

### ISSUE THREAD

**Issue by jpruiz114** [theseer/phpdox#201] opened 2015-02-12 00:22 UTC
![shot](https://cloud.githubusercontent.com/assets/4614970/6159426/3ce623ee-b223-11e4-9793-748721aca36e.png)

Trying to use if for the first time this happened:

php phpdox.phar

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.6.5 (WINNT)
PHPDox Version: 0.7.0
ErrorException: E_WARNING
Location: phar://C:/Development/Personal/github/phpdox-dependencies/phpdox.phar/phpdox/shared/Version.php (Line 62)

date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

#0 phar://C:/Development/Personal/github/phpdox-dependencies/phpdox.phar/phpdox/shared/Version.php(62): date()
#1 phar://C:/Development/Personal/github/phpdox-dependencies/phpdox.phar/phpdox/CLI.php(200): TheSeer\phpDox\Version::getInfoString()
#2 phar://C:/Development/Personal/github/phpdox-dependencies/phpdox.phar/phpdox/CLI.php(162): TheSeer\phpDox\CLI->showVersion()
#3 C:\Development\Personal\github\phpdox-dependencies\phpdox.phar(460): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment] 2015-02-12 00:42
Duplicate of #103.

Your PHP environment is lagging a time zone setting as the error message states.

**Closed by theseer** 2015-02-12 00:42 UTC
