### ISSUE TITLE
Class 'PHP_Timer' not found

### ISSUE THREAD

**Issue by MisatoTremor** [theseer/phpdox#245] opened 2015-09-10 10:53 UTC
```
Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.6.11 (Darwin)
PHPDox Version: 0.8.1
ErrorException: E_ERROR
Location: phar:///usr/local/bin/phpdox/phpdox/logger/ShellProgressLogger.php (Line 131)

Class 'PHP_Timer' not found

No stacktrace available
```

**Comment by theseer** [comment] 2015-09-10 13:03
Duplicate of #238

**Closed by theseer** 2015-09-10 13:03 UTC

**Comment by MisatoTremor** [comment] 2015-09-10 13:11
My apologies. I now see that I only searched in open issues before opening this one.
