### ISSUE TITLE
Use of undefined constant ENT_DISALLOWED - assumed 'ENT_DISALLOWED'

### ISSUE THREAD

**Issue by gimli2** [theseer/phpdox#202] opened 2015-02-13 15:52 UTC
Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.3.6 (WINNT)
PHPDox Version: 0.7.0
ErrorException: E_NOTICE
Location: phar://F:/web-localhost/phpDox.phar/phpdox/collector/project/Tokenizer
.php (Line 138)

Use of undefined constant ENT_DISALLOWED - assumed 'ENT_DISALLOWED'

#0 phar://F:/web-localhost/phpDox.phar/phpdox/collector/project/Tokenizer.php(10
5): TheSeer\phpDox\Collector\Tokenizer->addToken()
#1 phar://F:/web-localhost/phpDox.phar/phpdox/collector/project/SourceFile.php(8
1): TheSeer\phpDox\Collector\Tokenizer->toXML()
#2 phar://F:/web-localhost/phpDox.phar/phpdox/collector/project/Project.php(352)
: TheSeer\phpDox\Collector\SourceFile->getTokens()
#3 phar://F:/web-localhost/phpDox.phar/phpdox/collector/project/Project.php(270)
: TheSeer\phpDox\Collector\Project->saveSources()
#4 phar://F:/web-localhost/phpDox.phar/phpdox/Application.php(138): TheSeer\phpD
ox\Collector\Project->save()
#5 phar://F:/web-localhost/phpDox.phar/phpdox/CLI.php(148): TheSeer\phpDox\Appli
cation->runCollector()
#6 F:\web-localhost\phpDox.phar(460): TheSeer\phpDox\CLI->run()

**Comment by joskfg** [comment] 2015-02-17 18:16
I have the same problem. The constant is defined in PHP5.4 and I'm using PHP5.3 so the constant is undefined. The composer.json says that the package is compatible with PHP >= 5.3.3 but it isn't true just now.

Can you fix it?

**Comment by theseer** [comment] 2015-02-17 18:27
This is indeed a bug in 0.7.0 and has already been fixed in dev master.
Duplicate of #193.

**Closed by theseer** 2015-02-17 18:27 UTC

**Comment by ginside** [comment] 2015-03-30 12:52
Hello, as mentionned in the first message of this issue, op has runned phpdox through a phar archive. I had the same issue when trying to use phpdox through a phar downloaded today. Do you know when the fix will be included into a phar release?
