### ISSUE TITLE
fDOMdocument not found

### ISSUE THREAD

**Issue by v0idpwn** [theseer/phpdox#365] opened 2019-05-29 17:26 UTC
phpDox 0.12.0-dev - Copyright (C) 2010 - 2019 by Arne Blankerts and Contributors

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b (Linux)
PHPDox Version: 0.12.0-dev
Exception: Error (Code: 0)
Location: /home/v0idpwn/proj/maduro/vendor/theseer/phpdox/src/config/ConfigLoader.php (Line 78)

Class 'TheSeer\fDOM\fDOMDocument' not found

#0 /home/v0idpwn/proj/maduro/vendor/theseer/phpdox/src/config/ConfigLoader.php(35): TheSeer\phpDox\ConfigLoader->createInstanceFor()
#1 /home/v0idpwn/proj/maduro/vendor/theseer/phpdox/src/CLI.php(214): TheSeer\phpDox\ConfigLoader->load()
#2 /home/v0idpwn/proj/maduro/vendor/theseer/phpdox/src/CLI.php(71): TheSeer\phpDox\CLI->loadConfig()
#3 /home/v0idpwn/proj/maduro/vendor/theseer/phpdox/phpdox(68): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment] 2019-05-29 20:09
I can't reproduce this.

Any pointer on how you managed this to happen?

**Comment by v0idpwn** [comment] 2019-05-29 20:21
It was working fine yesterday. Maybe I messed up with composer, but I don't know...

**Comment by theseer** [comment] 2019-05-29 21:01
Not sure there's much I can do here.

I'll close this. Feel free to add another comment if you managed reproducible this after fixing your composer installation.

**Closed by theseer** 2019-05-29 21:01 UTC
