### ISSUE TITLE
HTML report missing // odd phpdox version

### ISSUE THREAD

**Issue by ZyanKLee** [theseer/phpdox#209] opened 2015-03-19 11:00 UTC
encountered an error while building our project with gitlab-ci. some oddities noticed:

```
phpdox --version
phpDox 0.0.8-688-gf57e304 - Copyright (C) 2010 - 2015 by Arne Blankerts
```

which SHOULD read something like 0.6.6.* - at least thats what composer told us:
```
# composer update 
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing theseer/phpdox (0.6.5)
  - Installing theseer/phpdox (0.6.6.1)
    Downloading: 100%         
```

phpdox error:

```
phpdox:
     [exec] phpDox 0.0.8-688-gf57e304 - Copyright (C) 2010 - 2015 by Arne Blankerts
     [exec] 
     [exec] [19.03.2015 - 11:13:45] Using config file './phpdox.xml'
     [exec] [19.03.2015 - 11:13:45] Registered collector backend 'parser'
     [exec] [19.03.2015 - 11:13:45] Registered enricher 'build'
     [exec] [19.03.2015 - 11:13:45] Registered enricher 'git'
     [exec] [19.03.2015 - 11:13:45] Registered enricher 'checkstyle'
     [exec] [19.03.2015 - 11:13:45] Registered enricher 'pmd'
     [exec] [19.03.2015 - 11:13:45] Registered enricher 'phpunit'
     [exec] [19.03.2015 - 11:13:45] Registered enricher 'phploc'
     [exec] [19.03.2015 - 11:13:45] Registered output engine 'xml'
     [exec] [19.03.2015 - 11:13:45] Registered output engine 'html'
     [exec] [19.03.2015 - 11:13:45] Starting to process project 'project-1'
     [exec] [19.03.2015 - 11:13:45] Starting collector
     [exec] [19.03.2015 - 11:13:45] Scanning directory './src' for files to process
     [exec] 
     [exec] ..................................................	[50]
     [exec] ..................................................	[100]
     [exec] ..................................................	[150]
     [exec] ..................................................	[200]
     [exec] ..................................................	[250]
     [exec] ..................................................	[300]
     [exec] ..................................................	[350]
     [exec] ..........                                        	[360]
     [exec] 
     [exec] [19.03.2015 - 11:13:53] Saving results to directory './build/api/xml'
     [exec] [19.03.2015 - 11:13:53] Resolving inheritance
     [exec] 
     [exec] ..................................................	[50]
     [exec] ..................................................	[100]
     [exec] ..................................................	[150]
     [exec] ..................................................	[200]
     [exec] ..................................................	[250]
     [exec] ..................................................	[300]
     [exec] ..................................................	[350]
     [exec] 
     [exec] 
     [exec] Oups... phpDox encountered a problem and has terminated!
     [exec] 
     [exec] It most likely means you've found a bug, so please file a report for this
     [exec] and paste the following details and the stacktrace (if given) along:
     [exec] 
     [exec] PHP Version: 5.5.9-1ubuntu4.6 (Linux)
     [exec] PHPDox Version: 0.0.8-688-gf57e304
     [exec] ErrorException: E_NOTICE 
     [exec] Location: /home/gitlab-runner/tmp/builds/project-1/vendor/theseer/phpdox/src/Application.php (Line 148)
     [exec] 
     [exec] Array to string conversion
     [exec] 
     [exec] #0 /home/gitlab-runner/tmp/builds/project-1/vendor/theseer/phpdox/src/Application.php(148): join()
     [exec] #1 /home/gitlab-runner/tmp/builds/project-1/vendor/theseer/phpdox/src/CLI.php(148): TheSeer\phpDox\Application->runCollector()
     [exec] #2 /home/gitlab-runner/tmp/builds/project-1/vendor/theseer/phpdox/composer/bin/phpdox(30): TheSeer\phpDox\CLI->run()
```

**Comment by theseer** [comment] 2015-03-19 16:25
Version 0.6.6 is _really_ old. You should at least be using 0.7.0 or, probably better right now, even dev-master. There will be an 0.8.0. soon.

Can you please verify if the problem you reported still exists in dev-master?

Regarding the version reported: That is a known bug of the version resolving when installed via composer and will (probably) be fixed for 0.8.0.

**Comment by ZyanKLee** [comment] 2015-03-20 16:08
I gave it a quick run with 0.7.0 - the problem still exists there. next I did this:

```
$ cd /home/zyanklee/Projekte
$ git clone git@github.com:theseer/phpdox.git
$ cd phpdox
$ composer install
$ cd ../project-1
$ ../phpdox/phpdox 

phpDox 0.7.0-100-g0a4f331 - Copyright (C) 2010 - 2015 by Arne Blankerts

[20.03.2015 - 16:04:59] Using config file './phpdox.xml'
[20.03.2015 - 16:04:59] Registered collector backend 'parser'
[20.03.2015 - 16:04:59] Registered enricher 'build'
[20.03.2015 - 16:04:59] Registered enricher 'git'
[20.03.2015 - 16:04:59] Registered enricher 'checkstyle'
[20.03.2015 - 16:04:59] Registered enricher 'phpcs'
[20.03.2015 - 16:04:59] Registered enricher 'pmd'
[20.03.2015 - 16:04:59] Registered enricher 'phpunit'
[20.03.2015 - 16:04:59] Registered enricher 'phploc'
[20.03.2015 - 16:04:59] Registered output engine 'xml'
[20.03.2015 - 16:04:59] Registered output engine 'html'
[20.03.2015 - 16:04:59] Starting to process project 'project-1'
[20.03.2015 - 16:04:59] Configuration change detected - cleaning cache
[20.03.2015 - 16:04:59] Starting collector
[20.03.2015 - 16:04:59] Scanning directory '/home/zyanklee/Projekte/project-1/src' for files to process

..................................................	[50]
..................................................	[100]
..................................................	[150]
..................................................	[200]
..................................................	[250]
..................................................	[300]
..................................................	[350]
.........                                         	[359]

[20.03.2015 - 16:05:03] Saving results to directory '/home/zyanklee/Projekte/project-1/build/api/xml'
[20.03.2015 - 16:05:05] Resolving inheritance

..................................................	[50]
..........................

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.5.9-1ubuntu4.7 (Linux)
PHPDox Version: 0.7.0-100-g0a4f331
ErrorException: E_ERROR 
Location: /home/zyanklee/Projekte/phpdox/src/collector/project/AbstractUnitObject.php (Line 346)

Call to a member function setAttribute() on a non-object

No stacktrace available
```

**Comment by ZyanKLee** [comment] 2015-03-20 16:10
ahh, and our phpdox.xml:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<phpdox xmlns="http://xml.phpdox.net/config">
    <project name="project-1" source="${basedir}/src" workdir="${basedir}/build/api/xml">
        <collector backend="parser"/>

        <generator output="${basedir}/build/api">
            <enrich base="${basedir}/build/logs">
                <source type="build" />
                <source type="git">
                    <history enabled="true" limit="15" />
                </source>
                <source type="checkstyle" />
                <source type="pmd" />
                <source type="phploc" />
                <source type="phpunit">
                    <coverage path="" />
                </source>
            </enrich>

            <build engine="html" output="html"/>
        </generator>
    </project>
</phpdox>
```

**Comment by theseer** [comment] 2015-03-21 10:55
While phpDox still crashes - which of course it shouldn't - the crash happens at a completely different locaiton and for a different reason.

The new crash is a duplicate of the reopened #190.

**Closed by theseer** 2015-03-21 10:55 UTC

**Comment by theseer** [comment] 2015-04-09 10:13
If you still need support with your configuration, please drop me a mail.
