### ISSUE TITLE
Composer - Conflict phpdox/phpunit ->php-timer ?

### ISSUE THREAD

**Issue by jkwasniak** [theseer/phpdox#331] opened 2018-04-11 06:47 UTC
The **phpdox** versions need currently phpunit/php-timer ^ 1.0, **phpunit** phpunit/php-timer 7.x ^ 2.0.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for theseer/phpdox ~0.11 -> satisfiable by theseer/phpdox[0.11.0].
    - theseer/phpdox 0.11.0 requires phpunit/php-timer ^1.0 -> satisfiable by phpunit/php-timer[1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
```
Is an update of the dependency on phpunit/php-timer ^ 2.0 planned?

My composeer.json

"require-dev": {
    "squizlabs/php_codesniffer": "~3.2",
    "roots/sage-installer": "~1.3",
    **"phpunit/php-timer": "^2.0",**
    **"phpunit/phpunit": "^7",**
    "phpmd/phpmd": "~2.6",
    "phan/phan": "~0.12",
    "phploc/phploc": "~4.0",
    **"theseer/phpdox": "~0.11",**
    "sensiolabs/security-checker": "~4.1",
    "johnpbloch/wordpress-core-installer": "^1.0",
    "johnpbloch/wordpress": "~4.9"
  },

**Comment by theseer** [comment] 2018-04-11 08:56
Duplicate of #328

**Closed by theseer** 2018-04-11 08:56 UTC
