### ISSUE TITLE
phpdox vs phpcpd

### ISSUE THREAD

**Issue by wickedOne** [theseer/phpdox#336] opened 2018-06-08 00:38 UTC
```
- Installation request for theseer/phpdox ^0.11.2 -> satisfiable by theseer/phpdox[0.11.2].
- Conclusion: remove phpunit/php-timer 2.0.0
```
apparently the latest version of theseer/phpdox and sebastianbergmann/phpcpd don't play nice together, any way around this?

**Comment by theseer** [comment] 2018-06-08 20:04
Duplicate of #328

**Closed by theseer** 2018-06-08 20:04 UTC
