### ISSUE TITLE
PHPUnit Enricher and XMLNS

### ISSUE THREAD

**Issue by fdirson-OpenGateway** [theseer/phpdox#364] opened 2019-05-16 17:50 UTC
Hi there,

The generated html doc doesn't display code coverage ( -> EMPTY)

I'm using "phpunit/phpunit" : "~7.5.2" and "theseer/phpdox" : "~0.12.0".
`PHP Version: 7.3.1 (WINNT)`
`PHPDox Version: 0.12.0-dev`

It seems that XMLNS for phpunit use only https URL (i can see it in $indexDom object (src/generator/engine/html/Html.php on line 211)".

I can fix it if i replace all 'xmlns:pu="http://schema.phpunit.de/coverage/1.0"' occurences by 'xmlns:pu="https://schema.phpunit.de/coverage/1.0"' in templates directory xsl files.
Now i can see 'PASSED' on classes list and good values in coverage section on class details.

But I still got no data on Overview HTML:
`Tests`
`Classes 	0`
`Methods 	0`

Regards,

F.DIRSON

**Comment by theseer** [comment] 2019-05-16 19:38
Sounds like a duplicate of #361.

If I'm wrong, pleaes add another comment and I'll reopen this.

**Closed by theseer** 2019-05-16 19:38 UTC

**Comment by theseer** [comment] 2019-05-16 19:40
With "overview html" you mean the index dashboard? The data there is based on phploc's output. It has nothing to do with coverage reports. If it reports `0` for all of them, that means phploc didn't find any tests.

**Comment by fdirson-OpenGateway** [comment] 2019-05-16 20:38
You're right, it's a duplicate of #361.
Thanks for overview html, so i'll check phploc reports.
