### ISSUE TITLE
New version of dependencies - php-parser and php-timer

### ISSUE THREAD

**Issue by peldax** [theseer/phpdox#347] opened 2018-11-22 23:59 UTC
It would be nice if new version used latest version of those dependencies as I have conflicts with other tools which require php-parser 4+ and php-timer 2+. I might look into it myself later, just leaving a note.

**Comment by theseer** [comment] 2018-11-23 11:51
Duplicate of #328.

See https://github.com/theseer/phpdox/issues/328#issuecomment-372602708 for details.

**Closed by theseer** 2018-11-23 11:51 UTC
