### ISSUE TITLE
X debug conflict

### ISSUE THREAD

**Issue by pbrilius** [theseer/phpdox#414] opened 2021-09-30 12:33 UTC
`phpdox --help` - after `phive install phpdox`:

```shell
phpDox 0.12.0 - Copyright (C) 2010 - 2021 by Arne Blankerts and Contributors



Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.4.16 (Linux)
PHPDox Version: 0.12.0
Exception: Error (Code: 0)
Location: phar:///home/povilasbrilius/.phive/phars/phpdox-0.12.0.phar/phpdox/shared/Environment.php (Line 46)

Call to undefined function TheSeer\phpDox\xdebug_disable()

#0 phar:///home/povilasbrilius/.phive/phars/phpdox-0.12.0.phar/phpdox/CLI.php(50): TheSeer\phpDox\Environment->ensureFitness()
#1 /home/povilasbrilius/.phive/phars/phpdox-0.12.0.phar(485): TheSeer\phpDox\CLI->run()

```

**Comment by theseer** [comment] 2021-09-30 13:32
Duplicate of #409

**Closed by theseer** 2021-09-30 13:32 UTC
