### ISSUE TITLE
E_WARNING in phar:///usr/local/bin/phpdox/vendor/theseer/fxsl/src/fxsltprocessor.php (Line 192)

### ISSUE THREAD

**Issue by tomekstach** [theseer/phpdox#301] opened 2017-01-17 05:58 UTC
After installation the phploc, I get something like this:

PHP Version: 7.0.14 (Darwin)
PHPDox Version: 0.9.0
ErrorException: E_WARNING 
Location: phar:///usr/local/bin/phpdox/vendor/theseer/fxsl/src/fxsltprocessor.php (Line 192)

XSLTProcessor::transformToDoc(): No stylesheet associated to this object

No stacktrace available

**Comment by tomekstach** [comment] 2017-01-17 11:02
I have this problem only on OS X - on ubuntu everything is OK.

And on OS X I have also something like this:

```....I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/components.xsl"
I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/functions.xsl"
I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/synopsis.xsl"


Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.0.14 (Darwin)
PHPDox Version: 0.9.0
Exception: TypeError (Code: 0)
Location: phar:///usr/local/bin/phpdox/phpdox/generator/engine/AbstractEngine.php (Line 59)

Argument 1 passed to TheSeer\phpDox\Generator\Engine\AbstractEngine::saveDomDocument() must be an instance of DOMDocument, boolean given, called in phar:///usr/local/bin/phpdox/phpdox/generator/engine/html/Html.php on line 210```

**Comment by theseer** [comment] 2017-01-21 12:28
Duplicate of #255.

**Closed by theseer** 2017-01-21 12:28 UTC
